#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2018 Petr Vorel <pvorel@suse.cz>
# Copyright (c) International Business Machines Corp., 2005
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TESTFUNC="do_test"
TST_SETUP="do_setup"
TST_CLEANUP="restore_ipaddr"
TST_NEEDS_CMDS="ip"
TST_CNT=$NS_TIMES

# TODO: really?
TST_NEEDS_TMPDIR=1

. tst_net_stress.sh

do_setup()
{
	# FIXME: remove duplicity
	mask=$IPV4_LPREFIX
	udp_size=1472
	if [ "$TST_IPV6" ]; then
		mask=$IPV6_LPREFIX
		udp_size=1452
	fi
	netstress_setup
	tst_res TINFO "change IPv$TST_IPVER route destination $NS_TIMES times"
}

do_test()
{
	local iface=$(tst_iface)
	local addr new_rt

	new_rt="$(tst_ipaddr_un $1)/$mask"
	addr="$(tst_ipaddr_un $1 1)"

	tst_res TINFO "testing route '$new_rt'"
	tst_rhost_run -c "ip addr add $addr/$mask dev $(tst_iface rhost)" # FIXME: new

	ROD ip route add $new_rt dev $iface
	ROD ip neigh replace $addr lladdr $(tst_hwaddr rhost) nud permanent dev $iface

	# Load the route with one UDP datagram
	#addr="10.23.99.1" # bad address on different subnet is correctly detected by ns-udpsender
	addr="$(tst_ipaddr_un $1 99)" # FIXME: non existed address on the same subnet is not detected by ns-udpsender
	EXPECT_PASS ns-udpsender -f $TST_IPVER -D $addr -p $1 -o -s $udp_size

	ROD ip neigh del $addr lladdr $(tst_hwaddr rhost) dev $iface
	ROD ip route del $new_rt dev $iface
	tst_rhost_run -c "ip addr del $addr/$mask dev $(tst_iface rhost)" # FIXME: new
}

tst_run
