#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2018 Petr Vorel <pvorel@suse.cz>
# Copyright (c) International Business Machines Corp., 2005
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TESTFUNC="do_test"
TST_SETUP="netstress_setup"
TST_CLEANUP="restore_ipaddr"
TST_NEEDS_CMDS="ip"

. tst_net_stress.sh

do_test()
{
	local iface=$(tst_iface)
	local cnt=1
	local addr new_rt

	local udp_size=1472
	local mask=24
	if [ "$TST_IPV6" ]; then
		udp_size=1452
		mask=64
	fi

	tst_res TINFO "change IPv$ipver route destination $NS_TIMES times"

	while [ $cnt -le $NS_TIMES ]; do
		new_rt="$(tst_ipaddr_un $cnt)/$mask"
		addr="$(tst_ipaddr_un $cnt 1)"

		ROD ip route add $new_rt dev $iface
		ROD ip neigh replace $addr lladdr $(tst_hwaddr rhost) nud permanent dev $iface

		# Load the route with one UDP datagram
		ROD ns-udpsender -f $ipver -D $addr -p $cnt -o -s $udp_size

		ROD ip neigh del $addr lladdr $(tst_hwaddr rhost) dev $iface
		ROD ip route del $new_rt dev $iface

		cnt=$(($cnt + 1))
	done

	tst_res TPASS "test is finished correctly"
}

tst_run
