#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2019 Petr Vorel <pvorel@suse.cz>
# Copyright (c) International Business Machines Corp., 2005
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TESTFUNC="do_test"
TST_SETUP="do_setup"
TST_CLEANUP="restore_ipaddr"
TST_NEEDS_CMDS="ip"
TST_CNT=$NS_TIMES

. tst_net_stress.sh

do_setup()
{
	# FIXME: remove duplicity
	mask=$IPV4_LPREFIX
	dad=
	if [ "$TST_IPV6" ]; then
		mask=$IPV6_LPREFIX
		udp_size=1452
		dad="nodad"
	fi
	netstress_setup
	tst_res TINFO "change IPv$TST_IPVER route gateway $NS_TIMES times"

	rt="$(tst_ipaddr_un 1 0)/$mask"
	addr="$(tst_ipaddr_un 1 1)"
	tst_rhost_run -s -c "ip addr add $addr/$mask dev $(tst_iface rhost)"
}

do_test()
{
	local iface=$(tst_iface)
	local new_gw="$(tst_ipaddr_un 1 $(($1 + 1)))"

	tst_res TINFO "testing gw '$new_gw'"

	echo "ROD ip addr add $new_gw/$mask dev $(tst_iface)"
	ROD ip addr add $new_gw/$mask dev $(tst_iface) $dad
	ip addr |grep $new_gw/$mask
	ping -c1 $new_gw

	ip -$TST_IPVER addr; ip -$TST_IPVER route # FIXME: debug

	echo "ROD ip route replace $rt dev $iface via $new_gw" # FIXME: debug
	ROD ip route replace $rt dev $iface via $new_gw

	ROD ip neigh replace $addr lladdr $(tst_hwaddr rhost) nud permanent dev $iface

	EXPECT_PASS ns-udpsender -f $TST_IPVER -D $addr -p $1 -o -s $udp_size

	ROD ip neigh del $addr lladdr $(tst_hwaddr rhost) dev $iface
	ROD ip route del $rt dev $iface via $new_gw
	ROD ip addr del $new_gw/$mask dev $(tst_iface)
}

tst_run
