#!/bin/sh
# Copyright (c) International Business Machines  Corp., 2006
# Copyright (c) 2017 Petr Vorel <pvorel@suse.cz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Verify the kernel is not crashed when the interface of an IPv4 route is
# changed frequently.
#
# Setup: testcases/network/stress/README
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TOTAL=2

. route4-lib.sh

TST_CLEANUP="do_cleanup"

RHOST_DST_ADDR=$(tst_ipaddr_un_ip $DST_NETWORK_OCTET_3 5)

do_setup()
{
	local link_num=0
	local lhost_ip rhost_ip

	route_setup

	[ $LINK_TOTAL -lt 2 ] && \
		tst_brkm TCONF "this test case requires more than one test link in LHOST_HWADDRS variable"

	while [ $link_num -lt $LINK_TOTAL ]; do
		lhost_ip=$(tst_ipaddr_un_ip $link_num $LHOST_IPV4_HOST)
		rhost_ip=$(tst_ipaddr_un_ip $link_num $RHOST_IPV4_HOST)
		tst_add_ipaddr_stress lhost $lhost_ip $link_num
		tst_add_ipaddr_stress rhost $rhost_ip $link_num

		check_connectivity $(tst_iface lhost $link_num) $rhost_ip
		link_num=$(($link_num + 1))
	done

	tst_add_ipaddr_stress rhost $RHOST_DST_ADDR
}

do_cleanup()
{
	local link_num=0

	netstress_cleanup

	while [ $link_num -lt $LINK_TOTAL ]; do
		lhost_ip=$(tst_ipaddr_un_ip $link_num $LHOST_IPV4_HOST)
		rhost_ip=$(tst_ipaddr_un_ip $link_num $RHOST_IPV4_HOST)
		ip addr del $lhost_ip/$IPV4_NETMASK_NUM dev $(tst_iface lhost $link_num)
		tst_rhost_run -c "ip addr del $rhost_ip/$IPV4_NETMASK_NUM dev $(tst_iface rhost $link_num)"
		link_num=$(($link_num + 1))
	done
}

do_setup

for cmd_name in 'rt_cmd' 'ip_cmd'; do
	route_test_change "if" $cmd_name $RHOST_DST_ADDR
done

tst_exit
