#!/bin/sh
# Copyright (c) International Business Machines  Corp., 2006
# Copyright (c) 2017 Petr Vorel <pvorel@suse.cz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Verify the kernel is not crashed when the IPv4 route is modified by
# ICMP Redirects frequently.
#
# Setup: testcases/network/stress/README
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TOTAL=1

. route4-lib.sh

TST_CLEANUP="do_cleanup"

SYSFS_ACCEPT_REDIRECTS=
SYSFS_SECURE_REDIRECTS=

do_cleanup()
{
	kill_daemon ns-udpsender
	restore_ipaddr
	restore_ipaddr rhost

	kill_daemon ns-icmp_redirector remote
	[ -n "$SYSFS_ACCEPT_REDIRECTS" ] && sysctl -qw net.ipv4.conf.$(tst_iface).accept_redirects=$SYSFS_ACCEPT_REDIRECTS
	[ -n "$SYSFS_SECURE_REDIRECTS" ] && sysctl -qw net.ipv4.conf.$(tst_iface).secure_redirects=$SYSFS_SECURE_REDIRECTS
}

do_setup()
{
	netstress_setup

	SYSFS_ACCEPT_REDIRECTS=$(sysctl -b net.ipv4.conf.$(tst_iface).accept_redirects)
	SYSFS_SECURE_REDIRECTS=$(sysctl -b net.ipv4.conf.$(tst_iface).secure_redirects)

	tst_add_ipaddr_stress

	# Run the redirector utility at the remote host
	tst_rhost_run -s -c "ns-icmp_redirector -I $(tst_iface rhost) -b"
}

test_body()
{
	local cnt=0
	tst_resm TINFO "changing IPv4 route by sending UDP packets with ns-udpsender $NS_TIMES times"
	while [ $cnt -lt $NS_TIMES ]; do
		ROD ns-udpsender -f 4 -D $(tst_ipaddr_un_host rhost 2) -p 7 -o -s 8
		cnt=$(($cnt + 1))
	done

	tst_resm TPASS "test is finished correctly"
}

do_setup
test_body

tst_exit
