#!/bin/sh
# Copyright (c) International Business Machines  Corp., 2006
# Copyright (c) 2017 Petr Vorel <pvorel@suse.cz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Verify the kernel is not crashed when the destination of an IPv4 route is
# changed frequently.
#
# Setup: testcases/network/stress/README
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TST_TOTAL=2

. route4-lib.sh

TST_CLEANUP="route_cleanup"

RHOST_GW=$(tst_ipaddr_un_ip $DST_NETWORK_OCTET_3 1)

do_setup()
{
	route_setup
	tst_add_ipaddr_stress lhost $RHOST_GW
}

do_setup

for cmd_name in 'rt_cmd' 'ip_cmd'; do
	route_test_change "dst" $cmd_name $RHOST_GW
done

tst_exit
