# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2019 Google, Inc.

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

LDLIBS := $(LDLIBS) $(CAP_LIBS)

include $(top_srcdir)/include/mk/generic_leaf_target.mk
